import { Activity, ArrowRight, CalendarDays, Check, Flame, MoreHorizontal, Play, Plus, Sparkles, Target, Timer } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Card, EmptyState, PageContainer, PageHeader, ProgressBar, SkeletonCard } from '../../components/ui'
import { useUIStore } from '../../store/uiStore'
import { useDashboard } from '../../hooks/useDashboard'
import { useCompleteTask, useSetTaskStatus } from '../../hooks/useTasks'
import { getApiErrorMessage } from '../../lib/api'
import type { Task } from '../../types/task'
import { useFinanceSummary } from '../../hooks/useFinance'
import { useHealthSummary } from '../../hooks/useHealth'
import { useFocusSessions, useFocusStart } from '../../hooks/useFocus'
import { AnimatedNumber } from '../../components/motion/AnimatedNumber'

export function HomePage() {
 const {data,isPending,isError,error,refetch}=useDashboard();const complete=useCompleteTask();const setStatus=useSetTaskStatus();const { focusMinutes, setFocusMinutes } = useUIStore()
 const toggle=(task:Task)=>task.status==='COMPLETED'?setStatus.mutate({id:task.id,status:'TODO'}):complete.mutate(task.id)
 if(isPending)return <PageContainer><PageHeader eyebrow="YOUR PERSONAL SPACE" title="Good morning" description="Loading your day…"/><div className="dashboard-grid"><SkeletonCard/><SkeletonCard/><SkeletonCard/><SkeletonCard/><SkeletonCard/><SkeletonCard/></div></PageContainer>
 if(isError||!data)return <PageContainer><PageHeader eyebrow="YOUR PERSONAL SPACE" title="Your day" description="NIVOR couldn't load your dashboard."/><Card className="dashboard-error"><div role="alert"><strong>Unable to load your dashboard.</strong><p>{getApiErrorMessage(error,'Check your connection and try again.')}</p><button className="button button-secondary" onClick={()=>void refetch()}>Try again</button></div></Card></PageContainer>
 return <PageContainer><PageHeader eyebrow={new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()} title="Your day" description="Here's what needs your attention today." action={<Link className="button button-secondary" to="/tasks"><Plus size={15}/> New task</Link>}/><div className="dashboard-grid">
  <Card className="completion-card"><div className="card-heading"><div><span className="card-icon"><Activity size={16}/></span><h2>Today's completion</h2></div><button className="quiet-icon" aria-label="More options"><MoreHorizontal size={18}/></button></div><div className="completion-content"><div className="completion-ring" aria-label={`${data.taskSummary.completionPercent} percent complete`}><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="49"/><circle className="ring-value" cx="60" cy="60" r="49" style={{'--ring-target': String(308-(308*data.taskSummary.completionPercent/100)),strokeDashoffset:308} as import('react').CSSProperties}/></svg><div><strong><AnimatedNumber value={data.taskSummary.completionPercent}/><span>%</span></strong><small>COMPLETE</small></div></div><div className="completion-details"><p>You're building<br/><b>good momentum.</b></p><span className="completion-count"><Check size={13}/> {<AnimatedNumber value={data.taskSummary.completed}/>} <i>of</i> {<AnimatedNumber value={data.taskSummary.total}/>} completed</span><small>{data.taskSummary.total-data.taskSummary.completed===0?'Your day is clear.':`${data.taskSummary.total-data.taskSummary.completed} steps left for today.`}</small></div></div><div className="card-bottom-caption"><span>DAILY MOMENTUM</span><span><i/> {data.taskSummary.completionPercent>=50?'On track':'Getting started'}</span></div></Card>
  <Card className="tasks-card"><div className="card-heading"><div><span className="card-icon"><Target size={16}/></span><h2>Today's tasks</h2><span className="count-badge"><AnimatedNumber value={data.taskSummary.total-data.taskSummary.completed}/></span></div><button className="quiet-icon" aria-label="More options"><MoreHorizontal size={18}/></button></div><div className="task-list">{data.todayTasks.length===0?<EmptyState title="No tasks for today" description="Your day has room. Add a task whenever you're ready."/>:data.todayTasks.slice(0,4).map(task=><button key={task.id} className={`task-row ${task.status==='COMPLETED'?'task-done':''}`} onClick={()=>toggle(task)}><span className={`task-check ${task.status==='COMPLETED'?'checked':''}`}>{task.status==='COMPLETED'&&<Check size={12}/>}</span><span className="task-title">{task.title}</span><span className={`priority priority-${task.status==='COMPLETED'?'done':task.priority.toLowerCase()}`}>{task.status==='COMPLETED'?'Done':task.priority}</span><time>{task.dueTime?.slice(0,5)??''}</time></button>)}</div><a className="card-link" href="/tasks">View all tasks <ArrowRight size={14}/></a></Card>
  <Card className="schedule-card"><div className="card-heading"><div><span className="card-icon"><CalendarDays size={16}/></span><h2>Your schedule</h2></div><button className="card-date">Today <span>⌄</span></button></div><div className="timeline">{data.todayEvents.length===0?<EmptyState title="Nothing scheduled" description="Your calendar is clear today."/>:data.todayEvents.slice(0,4).map((event,i)=><div className={`timeline-event ${i===0?'timeline-current':''}`} key={event.id}><time>{event.startTime.slice(11,16)}</time><span className="timeline-line"><i/></span><div><b>{event.title}</b><small>{event.location??(event.allDay?'All day':'Event')}</small></div></div>)}</div><a className="card-link" href="/planner">Open planner <ArrowRight size={14}/></a></Card>
  <Card className="habits-card"><div className="card-heading"><div><span className="card-icon"><Flame size={16}/></span><h2>Habits</h2></div><button className="quiet-icon" aria-label="More options"><MoreHorizontal size={18}/></button></div><div className="streak"><div><strong><AnimatedNumber value={data.habitSummary.completedToday}/><small> / <AnimatedNumber value={data.habitSummary.active}/></small></strong><span>done today</span></div><span className="streak-flame"><Flame size={22}/></span></div><div className="habit-summary-bar"><ProgressBar value={data.habitSummary.completionPercent}/></div><div className="habit-footer"><span>Today's consistency</span><span>{data.habitSummary.completionPercent}%</span></div></Card>
  <Card className="goals-card"><div className="card-heading"><div><span className="card-icon"><Target size={16}/></span><h2>Goals in motion</h2></div><button className="quiet-icon" aria-label="More options"><MoreHorizontal size={18}/></button></div><div className="goals-list">{data.goals.slice(0,3).map(goal=><div className="goal-row" key={goal.id}><div className="goal-top"><span>{goal.title}</span><b><AnimatedNumber value={goal.progress}/>%</b></div><ProgressBar value={goal.progress} className="goal-progress"/></div>)}</div>{data.goals.length===0&&<EmptyState title="No active goals" description="Add a goal to keep the bigger picture close."/>}<a className="card-link" href="/goals">View all goals <ArrowRight size={14}/></a></Card>
  <DashboardFocusCard minutes={focusMinutes} setMinutes={setFocusMinutes}/>
 </div><DashboardPart3/><div className="dashboard-bottom-note"><span><Sparkles size={13}/> Your day, with a little more clarity.</span><Link to="/analytics">Explore your progress <ArrowRight size={12}/></Link></div></PageContainer>
}

function DashboardFocusCard({minutes,setMinutes}:{minutes:number;setMinutes:(n:number)=>void}){const sessions=useFocusSessions(),start=useFocusStart();const active=sessions.data?.some(s=>s.status==='IN_PROGRESS');return <Card className="focus-card"><div className="focus-glow"/><div className="card-heading"><div><span className="card-icon"><Sparkles size={16}/></span><h2>Make room to focus</h2></div><span className="focus-status"><i/>{active?'IN PROGRESS':'READY'}</span></div><div className="focus-center"><div className="focus-timer-icon"><Timer size={23}/></div><div><strong><AnimatedNumber value={minutes}/><small>m</small></strong><span>ONE THING AT A TIME</span></div></div><div className="focus-duration">{[25,45,60].map(min=><button className={minutes===min?'selected':''} onClick={()=>setMinutes(min)} key={min}>{min} min</button>)}</div>{active?<Link className="focus-start" to="/focus"><Play size={14}/> Continue session</Link>:<button className="focus-start" disabled={start.isPending} onClick={()=>start.mutate({durationSeconds:minutes*60})}><Play size={14} fill="currentColor"/> Start focus</button>}<p>{start.isError?'Could not start session. Try again.':'Your focus session will be saved to history.'}</p></Card>}

function DashboardPart3(){const f=useFinanceSummary(),h=useHealthSummary(),sessions=useFocusSessions();const minutes=sessions.data?.filter(x=>x.status==='COMPLETED').reduce((n,x)=>n+Math.floor(x.durationSeconds/60),0)??0;return <section className="dashboard-advanced-grid" aria-label="Personal overview"><Link className="card dashboard-advanced-card" to="/finance"><span className="eyebrow">FINANCE · ALL TRANSACTIONS</span><strong>{f.isError?'—':`−${new Intl.NumberFormat(undefined,{style:'currency',currency:'INR',maximumFractionDigits:0}).format(f.data?.expenses||0)}`}</strong><small>{f.isError?'Summary unavailable':`Income ${new Intl.NumberFormat(undefined,{style:'currency',currency:'INR',maximumFractionDigits:0}).format(f.data?.income||0)} · Net ${new Intl.NumberFormat(undefined,{style:'currency',currency:'INR',maximumFractionDigits:0}).format(f.data?.netSavings||0)}`}</small></Link><Link className="card dashboard-advanced-card" to="/health"><span className="eyebrow">WELLNESS · RECENT</span><strong>{h.isError?'—':`${Math.round((h.data?.averageSleepMinutes||0)/60)}h average sleep`}</strong><small>{h.isError?'Summary unavailable':`${Math.round(h.data?.averageSteps||0).toLocaleString()} avg. steps · ${Math.round((h.data?.averageWaterMl||0)/250)} glasses water`}</small></Link><Link className="card dashboard-advanced-card" to="/focus"><span className="eyebrow">FOCUS · SAVED SESSIONS</span><strong>{sessions.isError?'—':`${minutes} min`}</strong><small>{sessions.isError?'History unavailable':`${sessions.data?.filter(x=>x.status==='COMPLETED').length||0} completed · view focus history`}</small></Link><Link className="card dashboard-advanced-card" to="/analytics"><span className="eyebrow">PERSONAL ANALYTICS</span><strong>See your patterns</strong><small>Tasks, habits, goals, and focus—based on recorded activity.</small></Link></section>}
