import { useEffect, useLayoutEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Activity, ArrowDown, ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Check, ChevronDown, CircleCheck, Clock3, FileText, HeartPulse, LayoutDashboard, Menu, PanelsTopLeft, Play, ShieldCheck, Sparkles, Target, Wallet, X } from 'lucide-react'
import { features } from '../../data/marketingData'
import { ProgressBar } from '../../components/ui'

const faqItems = [
 ['What is NIVOR?', 'NIVOR is a personal operating system that brings your plans, projects, knowledge, and everyday routines together in one thoughtful workspace.'],
 ['What can NIVOR AI do?', 'NIVOR AI is designed to help connect the context you choose to keep in your workspace, so it can help you plan, summarize, and find your next step.'],
 ['What can I manage inside NIVOR?', 'Tasks, schedules, notes, projects, goals, habits, journal entries, files, health, and personal finance all have a place.'],
 ['Can NIVOR help organize my schedule?', 'Yes. The planner brings your commitments and focus time into a clear daily view, so your plans can account for the time you actually have.'],
 ['Is NIVOR available on mobile?', 'NIVOR is designed to adapt across desktop, tablet, and mobile screens.'],
 ['How is my data protected?', 'Privacy is a core product principle. Detailed security controls and policies will be shared as the product moves toward launch.'],
]
function Brand() { return <Link to="/" className="brand landing-brand"><span className="brand-mark">n</span><span>NIVOR</span></Link> }
function DashboardMock() { return <div className="dashboard-mock"><div className="mock-sidebar"><Brand/><div className="mock-side-link selected"><LayoutDashboard size={14}/> Overview</div><div className="mock-side-link"><CalendarDays size={14}/> Planner</div><div className="mock-side-link"><Check size={14}/> Tasks</div><div className="mock-side-link"><FileText size={14}/> Notes</div><div className="mock-ai-tile"><Sparkles size={14}/><span>Ask NIVOR AI</span><ArrowUpRight size={12}/></div><div className="mock-person"><span className="avatar">A</span> Alex Morgan</div></div><div className="mock-main"><div className="mock-head"><span>Tuesday, October 1</span><span className="mock-avatar">A</span></div><div className="mock-welcome"><div><small>YOUR COMMAND CENTER</small><h3>Good morning, Alex</h3><p>Make space for what matters today.</p></div><button className="mock-plan"><Sparkles size={13}/> Plan my day</button></div><div className="mock-stats"><div><small>DAILY MOMENTUM</small><strong>72<span>%</span></strong><div className="mock-meter"><i/></div><em>6 of 8 tasks complete</em></div><div><small>FOCUS TIME</small><strong>2<span>h</span> 40<span>m</span></strong><em className="up-trend">↗ 18% this week</em><div className="mock-bars">{[30,50,38,70,46,82,60,92,55,73,42,65].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div></div><div className="mock-ai-card"><span className="mock-ai-icon"><Sparkles size={15}/></span><small>YOUR DAY, IN FOCUS</small><p>You have 2 deep-work blocks and one deadline today.</p><a>View your plan <ArrowRight size={12}/></a></div></div><div className="mock-lower"><div className="mock-tasks"><small>UP NEXT <span>VIEW ALL →</span></small>{[['Finish Java assignment','6:00 PM',false],['Complete project brief','8:00 PM',false],['ML revision','Done',true]].map(([a,b,c])=><div className="mock-task" key={a as string}><span className={`mock-check ${c ? 'checked' : ''}`}>{c ? '✓' : ''}</span><span>{a}</span><small>{b}</small></div>)}</div><div className="mock-schedule"><small>YOUR SCHEDULE <span>TODAY</span></small><div><i/>15:00 <b>Project work</b></div><div><i/>18:00 <b>Study session</b></div><div><i/>20:00 <b>Unwind</b></div></div></div></div></div> }
function VisualOrb({ type }: { type: string }) { return <div className={`visual-orb visual-${type}`}><div className="orb-core">{type === 'ai' ? <Sparkles/> : type === 'calendar' ? <CalendarDays/> : type === 'analytics' ? <Activity/> : type === 'finance' ? <Wallet/> : type === 'health' ? <HeartPulse/> : <PanelsTopLeft/>}</div><i/><b/><em/></div> }
function SectionLabel({ children }: { children: string }) { return <div className="section-label"><span/> {children}</div> }

export function LandingPage() {
 const [menuOpen, setMenuOpen] = useState(false); const [faqOpen, setFaqOpen] = useState(0); const [scrolled, setScrolled] = useState(false)
 useEffect(() => { const handleScroll = () => setScrolled(window.scrollY > 24); handleScroll(); window.addEventListener('scroll', handleScroll, { passive: true }); return () => window.removeEventListener('scroll', handleScroll) }, [])
 useLayoutEffect(() => {
  const sections = Array.from(document.querySelectorAll<HTMLElement>('.landing-page main > section:not(.hero), .landing-page .landing-footer'))
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) return
  sections.forEach(section => section.classList.add('landing-reveal'))
  const visibility = new Map<Element, number>()
  const observer = new IntersectionObserver(entries => {
   entries.forEach(entry => {
    visibility.set(entry.target, entry.isIntersecting ? entry.intersectionRatio : 0)
    if (entry.isIntersecting) entry.target.classList.add('is-visible')
   })
   const current = [...visibility.entries()].filter(([, ratio]) => ratio > 0).sort((a,b) => b[1]-a[1])[0]?.[0]
   sections.forEach(section => section.classList.toggle('is-current', section === current))
  }, { threshold: [0, 0.08, 0.2, 0.35, 0.5, 0.7], rootMargin: '-8% 0px -18% 0px' })
  sections.forEach(section => observer.observe(section))
  return () => { observer.disconnect(); sections.forEach(section => section.classList.remove('landing-reveal', 'is-visible', 'is-current')) }
 }, [])
 return <div className="landing-page"><nav className={`landing-nav ${scrolled ? 'scrolled' : ''}`}><div className="landing-nav-inner"><Brand/><div className="landing-links"><a href="#features">Features</a><a href="#platform">Platform</a><a href="#ai">AI</a><a href="#pricing">Pricing</a></div><div className="landing-nav-actions"><Link to="/login" className="landing-login">Log in</Link><Link to="/register" className="button button-primary landing-start">Get started <ArrowUpRight size={15}/></Link></div><button className="landing-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X/> : <Menu/>}</button></div>{menuOpen && <div className="landing-mobile-menu"><a href="#features" onClick={() => setMenuOpen(false)}>Features</a><a href="#platform" onClick={() => setMenuOpen(false)}>Platform</a><a href="#ai" onClick={() => setMenuOpen(false)}>AI</a><a href="#pricing" onClick={() => setMenuOpen(false)}>Pricing</a><Link to="/login">Log in</Link><Link to="/register">Get started free</Link></div>}</nav>
 <main><section className="hero"><div className="hero-grid"/><div className="hero-glow"/><div className="hero-content"><motion.div className="hero-kicker" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.5}}><span className="live-dot"/> THE PERSONAL OPERATING SYSTEM</motion.div><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.65,delay:.08}}>NIVOR: Unified<br/>Intelligence for<br/><span>Every Goal.</span></motion.h1><motion.p className="hero-copy" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.55,delay:.18}}>One intelligent workspace for tasks, schedules, notes, projects, goals, health, finance, and more.</motion.p><motion.div className="hero-actions" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.5,delay:.26}}><Link to="/register" className="button button-primary hero-cta">Get started free <ArrowRight size={16}/></Link><a href="#platform" className="hero-secondary"><span><Play size={12} fill="currentColor"/></span> Explore NIVOR</a></motion.div><div className="hero-proof"><div className="proof-avatars"><i>A</i><i>M</i><i>J</i><i>+</i></div><p>One space for <strong>everything you're building.</strong></p></div></div><div className="hero-orbit"><VisualOrb type="ai"/></div><div className="hero-mock-wrap"><DashboardMock/></div><div className="hero-scroll"><ArrowDown size={13}/> A clearer way forward</div><div className="hero-side-note">DESIGNED FOR YOUR WHOLE LIFE</div></section>
 <section className="trust-strip"><p>YOUR LIFE ISN'T ONE THING. YOUR WORKSPACE SHOULDN'T BE EITHER.</p><div>{[['◈','YOUR WORK'],['✳','YOUR IDEAS'],['⌁','YOUR HEALTH'],['↗','YOUR FUTURE']].map(([i,t])=><span key={t}><b>{i}</b>{t}</span>)}</div></section>
 <section className="landing-section feature-section" id="features"><div className="section-heading centered"><SectionLabel>ONE CONNECTED SYSTEM</SectionLabel><h2>Your whole life,<br/><span>in sync.</span></h2><p>All the moving parts of your life deserve a place that makes sense of them together.</p></div><div className="feature-bento"><article className="bento-card bento-large"><div className="bento-copy"><span className="feature-index">01 / INTELLIGENCE</span><h3>Clarity from<br/>the complexity.</h3><p>NIVOR AI connects the context you choose to keep, helping you move from a full mind to a clear next step.</p><a href="#ai">Meet your intelligent layer <ArrowRight size={14}/></a></div><VisualOrb type="ai"/></article><article className="bento-card bento-work"><span className="feature-index">02 / YOUR SPACE</span><h3>Everything has<br/>a place to land.</h3><p>Projects, notes, files, and ideas move together naturally.</p><div className="workspace-visual"><div className="workspace-sidebar"><i/><i/><i/><i/></div><div className="workspace-sheet"><small>PRODUCT LAUNCH</small><b>Q4 launch plan</b><span/><span/><span className="short"/><div className="workspace-tags"><i/><i/><i/></div></div><div className="workspace-note"><FileText size={14}/><b>Research notes</b><small>Updated just now</small></div></div></article><article className="bento-card bento-analytics"><span className="feature-index">03 / MOMENTUM</span><h3>Progress you<br/>can feel.</h3><p>Watch small, meaningful steps add up over time.</p><div className="analytics-visual"><div><small>WEEKLY FOCUS</small><strong>18h 24m <i>↗ 12%</i></strong></div><div className="analytics-chart">{[27,44,36,62,48,78,53,89,68,96,72,85,60,77].map((v,i)=><span key={i} style={{height:`${v}%`}}/>)}</div><div className="chart-days"><span>MON</span><span>TUE</span><span>WED</span><span>THU</span><span>FRI</span><span>SAT</span><span>SUN</span></div></div></article></div></section>
 <section className="ai-section" id="ai"><div className="ai-glow"/><div className="ai-layout"><div className="ai-copy"><SectionLabel>INTELLIGENCE, WITH CONTEXT</SectionLabel><h2>Meet your life<br/>where it <span>is.</span></h2><p className="ai-lede">Your intelligent layer across everything you do. NIVOR AI helps connect the dots, so you can spend less time sorting and more time moving forward.</p><ul className="ai-command-list">{['Plan my day','Summarize my notes','Analyze my spending','Create a study plan','Break down my project','Find what needs attention'].map((x,i)=><li key={x}><span>{['◷','≋','↗','✳','⊞','⌕'][i]}</span>{x}<ArrowUpRight size={13}/></li>)}</ul><Link to="/ai" className="text-link">Explore NIVOR AI <ArrowRight size={15}/></Link></div><div className="ai-interface"><div className="ai-window-head"><span className="ai-window-logo"><Sparkles size={14}/></span><div><strong>NIVOR AI</strong><small>Connected to your workspace</small></div><span className="ai-online"><i/> READY</span></div><div className="ai-conversation"><div className="ai-date">TUESDAY, OCTOBER 1</div><div className="ai-user-message">Help me plan a focused afternoon</div><div className="ai-response"><div className="ai-response-icon"><Sparkles size={15}/></div><div><small>HERE'S A PLAN THAT FITS</small><p>You have a project block at 3 PM and Java study at 6 PM. Let's protect your focus between them.</p><div className="ai-plan-card"><span><Clock3 size={13}/> 3:00 – 4:30 PM</span><b>Project deep work</b><small>90 minutes · Workspace</small></div><div className="ai-plan-card"><span><Clock3 size={13}/> 4:30 – 5:00 PM</span><b>Take a real break</b><small>30 minutes · Recharge</small></div><button className="ai-confirm"><Check size={14}/> Add plan to my day</button></div></div><div className="ai-suggestions"><button>Summarize today</button><button>What needs attention?</button><button>+ Ask something else</button></div></div><div className="ai-input"><span>Ask NIVOR anything...</span><button><ArrowRight size={14}/></button></div><div className="ai-privacy"><ShieldCheck size={11}/> Your workspace. Your context. Your control.</div></div></div></section>
 <section className="landing-section metrics-section" id="platform"><div className="section-heading"><SectionLabel>A LITTLE MORE PERSPECTIVE</SectionLabel><h2>Notice the progress<br/>you're already making.</h2><p>Personal analytics turn the invisible work of showing up into something you can see.</p></div><div className="metrics-board"><div className="metric-card metric-chart"><div className="metric-top"><div><small>PRODUCTIVITY SCORE</small><strong>82<span>/100</span></strong></div><BadgeTiny>↗ 8% this week</BadgeTiny></div><div className="productivity-graph"><svg viewBox="0 0 620 150" preserveAspectRatio="none" aria-label="Productivity rising through the week"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="var(--accent)" stopOpacity=".28"/><stop offset="1" stopColor="var(--accent)" stopOpacity="0"/></linearGradient></defs><path d="M0 125 C40 110 50 118 90 92 S155 101 190 75 S245 90 290 60 S360 85 395 50 S465 65 505 38 S570 50 620 15 V150 H0Z" fill="url(#chartFill)"/><path d="M0 125 C40 110 50 118 90 92 S155 101 190 75 S245 90 290 60 S360 85 395 50 S465 65 505 38 S570 50 620 15" fill="none" stroke="var(--accent)" strokeWidth="2.5"/></svg><div className="graph-days"><span>MON</span><span>TUE</span><span>WED</span><span>THU</span><span>FRI</span><span>SAT</span><span>SUN</span></div></div></div><div className="metric-small"><div className="metric-icon"><Clock3 size={17}/></div><small>FOCUS</small><strong>18h 24m</strong><span>Deep work, protected.</span><div className="tiny-bars">{[35,51,43,76,55,88,66].map((x,i)=><i key={i} style={{height:`${x}%`}}/>)}</div></div><div className="metric-small"><div className="metric-icon"><CircleCheck size={17}/></div><small>TASKS COMPLETED</small><strong>42</strong><span>Steady progress this week.</span><div className="task-dots">{Array.from({length:12}).map((_,i)=><i key={i} className={i<9?'filled':''}/>)}</div></div><div className="metric-small"><div className="metric-icon"><Activity size={17}/></div><small>HABIT CONSISTENCY</small><strong>87<span>%</span></strong><span>Showing up adds up.</span><ProgressBar value={87}/></div></div></section>
 <section className="workspace-section"><div className="workspace-copy"><SectionLabel>YOUR CONNECTED WORKSPACE</SectionLabel><h2>From first thought<br/>to <span>finished work.</span></h2><p>Keep your projects moving with the right pieces in reach. A task, a note, a timeline, and a file — all part of the same picture.</p><div className="workspace-points"><span><Check size={14}/> Projects that stay connected</span><span><Check size={14}/> Notes with their context intact</span><span><Check size={14}/> A timeline that makes sense</span></div><Link to="/workspace" className="text-link">Explore the workspace <ArrowRight size={15}/></Link></div><div className="workspace-product"><div className="wp-top"><div><small>YOUR WORKSPACE / PROJECTS</small><h3>Studio launch <span className="wp-status">IN MOTION</span></h3></div><button><Menu size={15}/></button></div><div className="wp-tabs"><span className="selected">Overview</span><span>Tasks <i>08</i></span><span>Notes</span><span>Files <i>12</i></span><span>Timeline</span></div><div className="wp-body"><div className="wp-progress"><div><small>PROJECT PROGRESS</small><strong>74%</strong><ProgressBar value={74}/><span>18 of 24 tasks complete</span></div><div className="wp-milestone"><span className="milestone-icon"><Target size={17}/></span><small>NEXT MILESTONE</small><b>Beta release</b><span>October 18 · 17 days</span></div></div><div className="wp-section-title">RECENT ACTIVITY <span>VIEW ALL →</span></div>{[['S','Finalize product brief','Completed by Alex','2h ago'],['N','User interview notes','Updated by Alex','4h ago'],['F','Product specs v2.pdf','Added to Files','Yesterday']].map(([i,title,meta,time])=><div className="wp-activity" key={title}><span className="wp-file-icon">{i==='S'?<Check size={14}/>:i==='N'?<FileText size={14}/>:<BookOpen size={14}/>}</span><div><b>{title}</b><small>{meta}</small></div><time>{time}</time></div>)}</div></div></section>
 <section className="landing-section modules-section"><div className="section-heading centered"><SectionLabel>BUILT AROUND YOUR LIFE</SectionLabel><h2>One rhythm.<br/><span>Every part of you.</span></h2><p>The tools you need, working together in a system that feels like yours.</p></div><div className="module-grid">{features.map((feature,i)=><article className="module-card" key={feature.title}><div className={`module-visual module-${i}`}><VisualOrb type={['ai','knowledge','analytics','workspace','calendar','health'][i]}/></div><div className="module-card-content"><span className="feature-index">0{i+1} / NIVOR</span><h3>{feature.title}</h3><p>{feature.text}</p><Link to={['/ai','/notes','/analytics','/workspace','/tasks','/health'][i]} aria-label={`Explore ${feature.title}`}><ArrowUpRight size={17}/></Link></div></article>)}</div></section>
 <section className="pricing-section" id="pricing"><div className="section-heading centered"><SectionLabel>ROOM TO GROW</SectionLabel><h2>Start with what<br/><span>you need.</span></h2><p>Begin with the essentials. Find your rhythm. Grow when you're ready.</p><small className="pricing-note">Plans and pricing are placeholders for product planning.</small></div><div className="pricing-grid">{[['NIVOR Free','A little more clarity.','Placeholder','The essentials to bring your day together.',['Personal command center','Tasks & daily planning','Notes & knowledge','Habit tracking']],['NIVOR Pro','Your whole system, connected.','Placeholder','More space for the way you work and live.',['Everything in Free','NIVOR AI workspace','Projects & analytics','Unlimited notes']],['NIVOR Ultimate','Space for everything ahead.','Placeholder','The complete NIVOR experience, at your pace.',['Everything in Pro','Advanced insights','Connected life systems','Priority support']]].map(([name,tag,price,desc,items],i)=><article className={`price-card ${i===1?'price-featured':''}`} key={name as string}>{i===1&&<div className="popular-label">A GOOD PLACE TO GROW</div>}<div className="price-head"><span>{name}</span><p>{tag}</p></div><div className="price-amount">{price as string}<small> / details coming later</small></div><p className="price-description">{desc as string}</p><Link to="/register" className={`button ${i===1?'button-primary':'button-outline'} price-cta`}>Get started free <ArrowRight size={14}/></Link><div className="price-divider"/><small className="plan-includes">A LITTLE MORE OF WHAT'S INCLUDED</small>{(items as string[]).map(x=><div className="price-feature" key={x}><Check size={14}/>{x}</div>)}</article>)}</div></section>
 <section className="testimonials-section"><div className="section-heading centered"><SectionLabel>MADE FOR REAL LIFE</SectionLabel><h2>A calmer space to<br/><span>find your next step.</span></h2><p>Illustrative perspectives on the kind of clarity NIVOR is built to support.</p><small className="demo-note">Placeholder testimonials · Not real users</small></div><div className="testimonial-grid">{[['JM','“I used to start every Monday feeling behind. Now I can see what matters and give it the space it needs.”','Jordan M.','Illustrative persona · Creative lead'],['AR','“It feels like my notes, plans, and projects finally know about each other. That changes the way I think.”','Alex R.','Illustrative persona · Graduate student'],['SK','“The best part is how quiet it feels. I can spend less energy organizing my life and more on living it.”','Sam K.','Illustrative persona · Independent founder']].map(([initials,quote,name,role],i)=><article className="testimonial-card" key={name}><div className="quote-mark">“</div><p>{quote}</p><div className="testimonial-person"><span className={`testimonial-avatar avatar-${i}`}>{initials}</span><div><b>{name}</b><small>{role}</small></div><span className="testimonial-stars">✳</span></div></article>)}</div></section>
 <section className="faq-section"><div className="faq-intro"><SectionLabel>GOOD QUESTIONS</SectionLabel><h2>A few things<br/>you might <span>wonder.</span></h2><p>Still curious? We're happy to talk.</p><a href="mailto:hello@nivor.example" className="text-link">Get in touch <ArrowRight size={15}/></a></div><div className="faq-list">{faqItems.map(([q,a],i)=><div className={`faq-item ${faqOpen===i?'open':''}`} key={q}><button onClick={() => setFaqOpen(faqOpen===i?-1:i)} aria-expanded={faqOpen===i}><span>{q}</span><i><ChevronDown size={16}/></i></button><div className="faq-answer" style={{gridTemplateRows:faqOpen===i?'1fr':'0fr'}}><p>{a}</p></div></div>)}</div></section>
 <section className="final-cta"><div className="cta-grid"/><div className="cta-orb cta-orb-one"/><div className="cta-orb cta-orb-two"/><div className="cta-content"><span className="cta-kicker"><Sparkles size={14}/> YOUR LIFE, IN SYNC</span><h2>Unified intelligence.<br/><span>Unlimited potential.</span></h2><p>Bring your tasks, goals, knowledge, projects and personal systems into one intelligent workspace.</p><Link to="/register" className="button button-primary hero-cta">Get started free <ArrowRight size={15}/></Link><small>No credit card. Just a clearer start.</small></div><div className="cta-decoration"><VisualOrb type="ai"/></div></section></main>
 <footer className="landing-footer"><div className="footer-main"><div className="footer-brand"><Brand/><p>A little more clarity<br/>for everything you're building.</p><div className="footer-social"><a href="#top" aria-label="Social link">in</a><a href="#top" aria-label="Social link">x</a><a href="#top" aria-label="Social link">◎</a></div></div><div className="footer-column"><b>PRODUCT</b><a href="#features">Features</a><a href="#ai">NIVOR AI</a><a href="#pricing">Pricing</a><Link to="/register">Get started</Link></div><div className="footer-column"><b>RESOURCES</b><a href="#faq">Documentation</a><a href="mailto:help@nivor.example">Help center</a><a href="#platform">What's new</a></div><div className="footer-column"><b>COMPANY</b><a href="#about">About NIVOR</a><a href="mailto:hello@nivor.example">Contact</a><Link to="/login">Sign in</Link></div><div className="footer-column"><b>LEGAL</b><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="#security">Security</a></div></div><div className="footer-bottom"><span>© 2026 NIVOR. A more thoughtful way to move forward.</span><span><i/> BUILT FOR THE WHOLE OF IT.</span></div></footer></div>
}
function BadgeTiny({children}:{children:React.ReactNode}) { return <span className="badge-tiny">{children}</span> }
