package com.nivor.file;
import com.nivor.common.exception.ResourceNotFoundException;import com.nivor.file.FileDtos.*;import com.nivor.project.*;import com.nivor.user.*;import com.nivor.ai.AiProvider;import java.io.*;import java.nio.*;import java.nio.charset.*;import java.util.*;import org.springframework.data.domain.PageRequest;import org.springframework.data.domain.Sort;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;
@Service @Transactional public class FileService{private static final long MAX=10*1024*1024;private final FileAssetRepository files;private final DocumentAnalysisRepository analyses;private final FileStorageService storage;private final UserService users;private final ProjectRepository projects;private final AiProvider ai;public FileService(FileAssetRepository f,DocumentAnalysisRepository a,FileStorageService s,UserService u,ProjectRepository p,AiProvider ai){files=f;analyses=a;storage=s;users=u;projects=p;this.ai=ai;}
 public List<FileView> list(String email,String query,String category,Long projectId){long uid=uid(email);String q=query==null?"":query.trim().toLowerCase(Locale.ROOT);String c=category==null||category.isBlank()?null:category.trim();return files.searchOwned(uid,q,c,projectId,PageRequest.of(0,500,Sort.unsorted())).getContent().stream().map(FileView::from).toList();}
 public FileView upload(String email,MultipartFile multipart,String category,Long projectId)throws IOException{if(multipart==null||multipart.isEmpty())throw new IllegalArgumentException("Choose a file to upload");if(multipart.getSize()>MAX)throw new IllegalArgumentException("File exceeds the 10 MB limit");String original=Optional.ofNullable(multipart.getOriginalFilename()).orElse("").replace('\\','/');original=original.substring(original.lastIndexOf('/')+1).strip();if(original.isBlank()||original.length()>240||original.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException("Filename is invalid");String ext=extension(original);if(!Set.of("txt","csv","pdf","docx","png","jpg","jpeg").contains(ext))throw new IllegalArgumentException("This file type is not supported");byte[] bytes=multipart.getBytes();String mime=validatedMime(ext,bytes);User user=users.getByEmail(email);FileAsset f=new FileAsset();f.setUser(user);if(projectId!=null)f.setProject(projects.findByIdAndUser_Id(projectId,user.getId()).orElseThrow(()->new ResourceNotFoundException("Project not found")));f.setOriginalName(original);f.setStoredName(UUID.randomUUID()+"."+ext);f.setMimeType(mime);f.setSize(bytes.length);f.setCategory(category==null||category.isBlank()?ext.toUpperCase(Locale.ROOT):category.trim());f.setStorageKey(f.getStoredName());storage.store(f.getStorageKey(),bytes);try{return FileView.from(files.save(f));}catch(RuntimeException ex){storage.delete(f.getStorageKey());throw ex;}}
 public FileView get(String email,long id){return FileView.from(owned(email,id));}
 public Download download(String email,long id)throws IOException{FileAsset f=owned(email,id);if(!storage.exists(f.getStorageKey()))throw new ResourceNotFoundException("Stored file not found");return new Download(f.getOriginalName(),f.getMimeType(),f.getSize(),storage.open(f.getStorageKey()));}
 public void delete(String email,long id)throws IOException{FileAsset f=owned(email,id);analyses.deleteAllByFile_IdAndUser_Id(id,f.getUser().getId());storage.delete(f.getStorageKey());files.delete(f);}
 public AnalysisView analyze(String email,long id){FileAsset file=owned(email,id);DocumentAnalysis a=new DocumentAnalysis();a.setFile(file);a.setUser(file.getUser());if(!ai.available()){a.setStatus(AnalysisStatus.FAILED);a.setSummary("Document analysis is unavailable: configure an AI provider first.");return AnalysisView.from(analyses.save(a));}String ext=extension(file.getOriginalName());if(!Set.of("txt","csv").contains(ext)){a.setStatus(AnalysisStatus.FAILED);a.setSummary("This format is stored securely, but document text extraction is not available yet. TXT and CSV analysis are supported when AI is configured.");return AnalysisView.from(analyses.save(a));}try(InputStream in=storage.open(file.getStorageKey())){byte[] bytes=in.readNBytes(60_001);if(bytes.length>60_000)throw new IllegalArgumentException("Documents above 60 KB cannot be sent for analysis yet.");String content=StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes)).toString();a.setStatus(AnalysisStatus.PROCESSING);analyses.saveAndFlush(a);String summary=ai.generate("Summarize the user-provided document. Identify its key topics and important points. Do not infer facts absent from the text. Return concise Markdown.",content);a.setSummary(summary.length()>12000?summary.substring(0,12000):summary);a.setStatus(AnalysisStatus.COMPLETED);}catch(Exception ex){a.setStatus(AnalysisStatus.FAILED);a.setSummary(ex instanceof IllegalArgumentException?ex.getMessage():"Analysis failed while reading or processing this document. Please try again later.");}return AnalysisView.from(analyses.save(a));}
 public AnalysisView analysis(String email,long id){owned(email,id);return analyses.findFirstByFile_IdAndUser_IdOrderByCreatedAtDesc(id,uid(email)).map(AnalysisView::from).orElse(null);}
 public String textForAi(String email,long id)throws IOException{FileAsset file=owned(email,id);if(!Set.of("txt","csv").contains(extension(file.getOriginalName())))throw new IllegalArgumentException("AI document reading currently supports TXT and CSV only.");try(InputStream in=storage.open(file.getStorageKey())){byte[] bytes=in.readNBytes(60_001);if(bytes.length>60_000)throw new IllegalArgumentException("Documents above 60 KB cannot be sent for analysis yet.");return StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes)).toString();}catch(CharacterCodingException ex){throw new IllegalArgumentException("Document text must be UTF-8.");}}
 private FileAsset owned(String e,long id){return files.findByIdAndUser_Id(id,uid(e)).orElseThrow(()->new ResourceNotFoundException("File not found"));}private long uid(String e){return users.getByEmail(e).getId();}
 private String extension(String name){int at=name.lastIndexOf('.');return at<0?"":name.substring(at+1).toLowerCase(Locale.ROOT);}
 private String validatedMime(String ext,byte[] b){if(ext.equals("pdf")){if(b.length<5||!new String(b,0,5,StandardCharsets.US_ASCII).equals("%PDF-"))throw new IllegalArgumentException("File content does not match PDF type");return "application/pdf";}if(ext.equals("png")){if(b.length<8||(b[0]&255)!=137||b[1]!=80||b[2]!=78||b[3]!=71)throw new IllegalArgumentException("File content does not match PNG type");return "image/png";}if(ext.equals("jpg")||ext.equals("jpeg")){if(b.length<3||(b[0]&255)!=255||(b[1]&255)!=216||(b[2]&255)!=255)throw new IllegalArgumentException("File content does not match JPEG type");return "image/jpeg";}if(ext.equals("docx")){if(b.length<4||b[0]!='P'||b[1]!='K')throw new IllegalArgumentException("File content does not match DOCX type");return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";}for(byte value:b)if(value==0)throw new IllegalArgumentException("Text files cannot contain binary data");try{StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(b));}catch(CharacterCodingException ex){throw new IllegalArgumentException("Text file must be UTF-8");}return ext.equals("csv")?"text/csv":"text/plain";}
 public record Download(String filename,String mimeType,long size,InputStream stream){}
}
