package com.nivor.ai;
import com.fasterxml.jackson.databind.*;import com.nivor.common.exception.ResourceNotFoundException;import com.nivor.ai.AiDtos.*;import com.nivor.note.NoteService;import com.nivor.note.dto.NoteRequest;import com.nivor.planner.CalendarEventService;import com.nivor.planner.dto.CalendarEventRequest;import com.nivor.task.*;import com.nivor.task.dto.TaskRequest;import com.nivor.user.*;import jakarta.validation.*;import java.time.LocalDateTime;import java.util.*;import org.springframework.stereotype.Service;
@Service public class AiActionService{private final AiActionRepository repo;private final AiConversationRepository convs;private final UserService users;private final TaskService tasks;private final CalendarEventService events;private final NoteService notes;private final ObjectMapper mapper;private final Validator validator;public AiActionService(AiActionRepository r,AiConversationRepository c,UserService u,TaskService t,CalendarEventService e,NoteService n,ObjectMapper m,Validator v){repo=r;convs=c;users=u;tasks=t;events=e;notes=n;mapper=m;validator=v;}
 public ActionView propose(String email,long conversationId,AiActionType type,JsonNode payload){if(!Set.of(AiActionType.CREATE_TASK,AiActionType.COMPLETE_TASK,AiActionType.DELETE_TASK,AiActionType.CREATE_EVENT,AiActionType.DELETE_EVENT,AiActionType.CREATE_NOTE).contains(type))throw new IllegalArgumentException("AI action type is not enabled");var user=users.getByEmail(email);AiConversation c=convs.findByIdAndUser_Id(conversationId,user.getId()).orElseThrow(()->new ResourceNotFoundException("Conversation not found"));AiAction a=new AiAction();a.setUser(user);a.setConversation(c);a.setType(type);a.setPayload(payload.toString());a.setStatus(AiActionStatus.PROPOSED);return view(repo.save(a));}
 public ActionView get(String email,long id){return view(owned(email,id));}
 public ActionView cancel(String email,long id){AiAction a=owned(email,id);if(a.getStatus()!=AiActionStatus.PROPOSED)throw new IllegalArgumentException("Only proposed actions can be cancelled");a.setStatus(AiActionStatus.CANCELLED);return view(repo.save(a));}
 public ActionView confirm(String email,long id){AiAction a=owned(email,id);if(a.getStatus()!=AiActionStatus.PROPOSED)throw new IllegalArgumentException("Only proposed actions can be confirmed");a.setStatus(AiActionStatus.CONFIRMED);repo.save(a);try{execute(email,a);a.setStatus(AiActionStatus.EXECUTED);a.setExecutedAt(LocalDateTime.now());return view(repo.save(a));}catch(RuntimeException ex){a.setStatus(AiActionStatus.FAILED);repo.save(a);throw ex;}}
 private void execute(String email,AiAction a){JsonNode p;try{p=mapper.readTree(a.getPayload());}catch(Exception ex){throw new IllegalArgumentException("Action payload is invalid");}switch(a.getType()){
 case CREATE_TASK->{TaskRequest r=read(p,TaskRequest.class);validate(r);tasks.create(email,r);}
 case COMPLETE_TASK->tasks.setStatus(email,id(p,"taskId"),TaskStatus.COMPLETED);
 case DELETE_TASK->tasks.delete(email,id(p,"taskId"));
 case CREATE_EVENT->{CalendarEventRequest r=read(p,CalendarEventRequest.class);validate(r);events.create(email,r);}
 case DELETE_EVENT->events.delete(email,id(p,"eventId"));
 case CREATE_NOTE->{NoteRequest r=read(p,NoteRequest.class);validate(r);notes.create(email,r);}
 default->throw new IllegalArgumentException("AI action type is not enabled");}}
 private long id(JsonNode n,String key){JsonNode v=n.get(key);if(v==null||!v.canConvertToLong()||v.asLong()<=0)throw new IllegalArgumentException("Action target is invalid");return v.asLong();}
 private <T>T read(JsonNode n,Class<T> c){try{return mapper.treeToValue(n,c);}catch(Exception e){throw new IllegalArgumentException("Action payload is invalid");}}private <T>void validate(T v){Set<ConstraintViolation<T>> errors=validator.validate(v);if(!errors.isEmpty())throw new IllegalArgumentException(errors.iterator().next().getMessage());}
 private AiAction owned(String e,long id){return repo.findByIdAndUser_Id(id,users.getByEmail(e).getId()).orElseThrow(()->new ResourceNotFoundException("Action not found"));}private ActionView view(AiAction a){try{return new ActionView(a.getId(),a.getType(),mapper.readTree(a.getPayload()),a.getStatus(),a.getCreatedAt());}catch(Exception ex){throw new IllegalStateException("Stored action is invalid");}}}
