package com.nivor.ai;
import com.fasterxml.jackson.databind.*;import com.nivor.ai.AiDtos.*;import com.nivor.common.exception.ResourceNotFoundException;import com.nivor.user.*;import jakarta.validation.Valid;import java.util.*;import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class AiService{private final AiProvider provider;private final AiConversationRepository conversations;private final AiMessageRepository messages;private final AiActionRepository actionRows;private final AiContextService context;private final AiActionService actions;private final UserService users;private final ObjectMapper mapper;private final AiRateLimiter rateLimiter;public AiService(AiProvider p,AiConversationRepository c,AiMessageRepository m,AiActionRepository ar,AiContextService x,AiActionService a,UserService u,ObjectMapper o,AiRateLimiter limiter){provider=p;conversations=c;messages=m;actionRows=ar;context=x;actions=a;users=u;mapper=o;rateLimiter=limiter;}
 public boolean available(){return provider.available();}public List<ConversationView> conversations(String e){return conversations.findAllByUser_IdOrderByUpdatedAtDesc(users.getByEmail(e).getId()).stream().limit(100).map(this::view).toList();}
 public ConversationView create(String e,CreateConversation r){AiConversation c=new AiConversation();c.setUser(users.getByEmail(e));c.setTitle(r.title()==null||r.title().isBlank()?"New conversation":r.title().trim());return view(conversations.save(c));}
 public ConversationView get(String e,long id){return view(owned(e,id));}public void delete(String e,long id){AiConversation c=owned(e,id);actionRows.deleteAllByConversation_IdAndUser_Id(id,c.getUser().getId());messages.deleteAll(messages.findAllByConversation_IdOrderByCreatedAtAsc(id));conversations.delete(c);}
 public List<MessageView> messages(String e,long id){owned(e,id);return messages.findAllByConversation_IdOrderByCreatedAtDesc(id,PageRequest.of(0,100)).stream().sorted(Comparator.comparing(AiMessage::getCreatedAt)).map(this::view).toList();}
 public ChatResponse chat(String e,ChatRequest r){rateLimiter.check(e);AiConversation c=r.conversationId()==null?newConversation(e,r.message()):owned(e,r.conversationId());c.setTitle(c.getTitle().equals("New conversation")?title(r.message()):c.getTitle());AiMessage userMsg=new AiMessage();userMsg.setConversation(c);userMsg.setRole(AiMessageRole.USER);userMsg.setContent(r.message().trim());messages.save(userMsg);conversations.save(c);if(!provider.available())return new ChatResponse(c.getId(),false,"AI is not configured yet.",List.of(),provider.providerName());String prior=messages.findAllByConversation_IdOrderByCreatedAtDesc(c.getId(),PageRequest.of(0,12)).stream().filter(m->m.getRole()!=AiMessageRole.SYSTEM).sorted(Comparator.comparing(AiMessage::getCreatedAt)).map(m->m.getRole()+": "+m.getContent()).reduce((a,b)->a+"\n"+b).orElse("");if(prior.length()>6000)prior=prior.substring(prior.length()-6000);String data=context.forRequest(e,r.message());String raw=provider.generate(prior,data);String text=raw;List<ActionView> proposals=new ArrayList<>();try{JsonNode root=mapper.readTree(raw);if(root.isObject()&&root.path("message").isTextual()){text=root.path("message").asText();JsonNode list=root.path("actions");if(list.isArray())for(JsonNode action:list){try{AiActionType type=AiActionType.valueOf(action.path("type").asText());JsonNode payload=action.path("payload");if(!payload.isObject())continue;proposals.add(actions.propose(e,c.getId(),type,payload));}catch(IllegalArgumentException ignored){}}}}catch(Exception ignored){}AiMessage answer=new AiMessage();answer.setConversation(c);answer.setRole(AiMessageRole.ASSISTANT);answer.setContent(text);messages.save(answer);return new ChatResponse(c.getId(),true,text,List.copyOf(proposals),provider.providerName());}
 public ChatResponse prompt(String e,String prompt){rateLimiter.check(e);if(!provider.available())return new ChatResponse(null,false,"AI is not configured yet.",List.of(),provider.providerName());return new ChatResponse(null,true,provider.generate(prompt,context.forRequest(e,prompt)),List.of(),provider.providerName());}
 public ChatResponse dailyBriefing(String e){String prompt="Plan my day with a brief, useful overview.";if(!provider.available())return new ChatResponse(null,false,"AI is not configured yet. Review today's tasks, events, habits, and active goals in your dashboard.",List.of(),provider.providerName());return prompt(e,prompt);}
 private AiConversation newConversation(String e,String first){AiConversation c=new AiConversation();c.setUser(users.getByEmail(e));c.setTitle(title(first));return conversations.save(c);}private String title(String s){String t=s.strip().replaceAll("\\s+"," ");return t.length()>64?t.substring(0,61)+"…":t;}private AiConversation owned(String e,long id){return conversations.findByIdAndUser_Id(id,users.getByEmail(e).getId()).orElseThrow(()->new ResourceNotFoundException("Conversation not found"));}private ConversationView view(AiConversation c){return new ConversationView(c.getId(),c.getTitle(),c.getCreatedAt(),c.getUpdatedAt());}private MessageView view(AiMessage m){return new MessageView(m.getId(),m.getRole(),m.getContent(),m.getCreatedAt());}}
