import { useEffect, useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, Search, Sparkles } from 'lucide-react'
import { useSearch } from '../../hooks/useSearch'
import type { SearchResult } from '../../types/advanced'
const commands = [{ group: 'NAVIGATION', title: 'Home', path: '/home' }, { group: 'NAVIGATION', title: 'Planner', path: '/planner' }, { group: 'NAVIGATION', title: 'NIVOR AI', path: '/ai' }, { group: 'NAVIGATION', title: 'Workspace', path: '/workspace' }, { group: 'NAVIGATION', title: 'Notes', path: '/notes' }, { group: 'NAVIGATION', title: 'Tasks', path: '/tasks' }, { group: 'NAVIGATION', title: 'Finance', path: '/finance' }, { group: 'NAVIGATION', title: 'Health', path: '/health' }, { group: 'NAVIGATION', title: 'Focus', path: '/focus' }, { group: 'AI ACTIONS', title: 'Plan my day', path: '/ai' }]
export function CommandPalette({ open, onClose }: { open: boolean; onClose: () => void }) {
 const [query, setQuery] = useState(''); const [active, setActive] = useState(0); const navigate = useNavigate(); const remote = useSearch(query.trim()); const dialogRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null); const previousFocus = useRef<HTMLElement | null>(null)
 const filtered = useMemo(() => commands.filter(c => c.title.toLowerCase().includes(query.toLowerCase())), [query])
 const remoteResults: SearchResult[] = Array.isArray(remote.data) ? remote.data as SearchResult[] : []
 const entries = useMemo(() => [...filtered.map(c => ({ title:c.title,path:c.path,group:c.group })), ...(query.trim()? remoteResults.map(r=>({title:r.title,path:r.path,group:r.type,description:r.description??undefined})):[])], [filtered,query,remoteResults])
 useEffect(() => { setActive(0) }, [query])
 useEffect(() => { if (!open) {setQuery('');return}; previousFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; requestAnimationFrame(() => inputRef.current?.focus()); return () => previousFocus.current?.focus() }, [open])
 useEffect(() => { if (!open) return; const key = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); if (e.key === 'ArrowDown') { e.preventDefault(); setActive(v => (v + 1) % Math.max(entries.length, 1)) } if (e.key === 'ArrowUp') { e.preventDefault(); setActive(v => (v - 1 + Math.max(entries.length, 1)) % Math.max(entries.length, 1)) } if (e.key === 'Enter' && entries[active]) { navigate(entries[active].path); onClose() } if (e.key === 'Tab' && dialogRef.current) { const focusable = [...dialogRef.current.querySelectorAll<HTMLElement>('input:not([disabled]),button:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')]; const first = focusable[0], last = focusable.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus() } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus() } } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [open, entries, active, navigate, onClose])
 return <AnimatePresence>{open && <motion.div className="palette-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose() }} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div ref={dialogRef} className="command-palette" role="dialog" aria-modal="true" aria-label="Command search" initial={{opacity:0, y:-10, scale:.98}} animate={{opacity:1, y:0, scale:1}} exit={{opacity:0, y:-8}}><div className="palette-search"><Search size={19}/><input ref={inputRef} placeholder="Search NIVOR or jump to..." value={query} onChange={e => setQuery(e.target.value)} aria-label="Search NIVOR or jump to" /><kbd aria-hidden="true">ESC</kbd></div><div className="palette-results" role="listbox" aria-label="Search results">{remote.isFetching&&query.trim()&&<p className="palette-empty" role="status">Searching your space…</p>}{entries.length === 0&&!remote.isFetching ? <p className="palette-empty" role="status">No results found</p> : entries.map((item, i) => <button key={`${item.group}-${item.title}-${i}`} role="option" aria-selected={active===i} className={`palette-result ${active === i ? 'selected' : ''}`} onMouseEnter={() => setActive(i)} onClick={() => { navigate(item.path); onClose() }}><span className="palette-result-icon">{item.group === 'AI ACTIONS' ? <Sparkles size={16}/> : <ArrowRight size={16}/>}</span><span className="palette-result-copy"><strong>{item.title}</strong>{'description' in item && typeof item.description === 'string' && <small>{item.description}</small>}</span><small>{item.group}</small></button>)}</div><div className="palette-footer"><span>↑↓ to navigate</span><span>↵ to open</span><span><Sparkles size={12}/> NIVOR command</span></div></motion.div></motion.div>}</AnimatePresence>
}
