package com.nivor.note;
import com.nivor.common.exception.ResourceNotFoundException;import com.nivor.note.dto.NoteRequest;import com.nivor.user.*;import java.util.*;import org.jsoup.Jsoup;import org.jsoup.safety.Safelist;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class NoteService{
private final NoteRepository notes;private final UserService users;public NoteService(NoteRepository n,UserService u){notes=n;users=u;}
@Transactional(readOnly=true)public List<Note> list(String email,String search,Boolean favorite,Boolean pinned,String category,String tag){Long id=users.getByEmail(email).getId();String q=search==null?null:search.toLowerCase(Locale.ROOT);return notes.findAllByUser_IdOrderByUpdatedAtDesc(id).stream().filter(n->q==null||q.isBlank()||n.getTitle().toLowerCase(Locale.ROOT).contains(q)||n.getContent()!=null&&Jsoup.parse(n.getContent()).text().toLowerCase(Locale.ROOT).contains(q)).filter(n->favorite==null||n.isFavorite()==favorite).filter(n->pinned==null||n.isPinned()==pinned).filter(n->category==null||category.equalsIgnoreCase(n.getCategory())).filter(n->tag==null||n.getTags().stream().anyMatch(tag::equalsIgnoreCase)).toList();}
@Transactional(readOnly=true)public Note get(String email,Long id){return owned(email,id);}@Transactional public Note create(String email,NoteRequest r){Note n=new Note();n.setUser(users.getByEmail(email));apply(n,r);return notes.save(n);}@Transactional public Note update(String email,Long id,NoteRequest r){Note n=owned(email,id);apply(n,r);return n;}
@Transactional public Note favorite(String email,Long id){Note n=owned(email,id);n.setFavorite(!n.isFavorite());return n;}@Transactional public Note pin(String email,Long id){Note n=owned(email,id);n.setPinned(!n.isPinned());return n;}@Transactional public void delete(String email,Long id){notes.delete(owned(email,id));}
private Note owned(String email,Long id){return notes.findByIdAndUser_Id(id,users.getByEmail(email).getId()).orElseThrow(()->new ResourceNotFoundException("Note not found"));}private void apply(Note n,NoteRequest r){n.setTitle(r.title().trim());n.setContent(r.content()==null?"":Jsoup.clean(r.content(),Safelist.basic()));n.setCategory(r.category());n.setTags(r.tags());if(r.favorite()!=null)n.setFavorite(r.favorite());if(r.pinned()!=null)n.setPinned(r.pinned());}
}
