package com.nivor.search;
import com.nivor.file.*;import com.nivor.user.UserService;import jakarta.persistence.EntityManager;import java.util.*;import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional(readOnly=true)public class SearchService{private final UserService users;private final EntityManager em;private final FileAssetRepository files;public SearchService(UserService u,EntityManager e,FileAssetRepository f){users=u;em=e;files=f;}
 public SearchDtos.SearchResponse search(String email,String query,String type,Integer requestedLimit){if(query==null||query.isBlank())return new SearchDtos.SearchResponse(List.of());if(query.length()>100)throw new IllegalArgumentException("Search is limited to 100 characters");int limit=requestedLimit==null?10:Math.max(1,Math.min(20,requestedLimit));String q="%"+query.trim().toLowerCase(Locale.ROOT)+"%";long uid=users.getByEmail(email).getId();Set<String> selected=type==null?Set.of("TASK","NOTE","PROJECT","FILE","GOAL","JOURNAL","EVENT"):Set.of(type.toUpperCase(Locale.ROOT));List<SearchDtos.Result> out=new ArrayList<>();
 if(selected.contains("TASK"))em.createQuery("select t from Task t where t.user.id=:uid and (lower(t.title) like :q or lower(coalesce(t.description,'')) like :q) order by t.updatedAt desc",com.nivor.task.Task.class).setParameter("uid",uid).setParameter("q",q).setMaxResults(limit).getResultList().forEach(t->out.add(new SearchDtos.Result("TASK",t.getId(),t.getTitle(),t.getDescription(),"/tasks",t.getUpdatedAt())));
 if(selected.contains("NOTE"))em.createQuery("select n from Note n where n.user.id=:uid and (lower(n.title) like :q or lower(coalesce(n.content,'')) like :q) order by n.updatedAt desc",com.nivor.note.Note.class).setParameter("uid",uid).setParameter("q",q).setMaxResults(limit).getResultList().forEach(n->out.add(new SearchDtos.Result("NOTE",n.getId(),n.getTitle(),null,"/notes",n.getUpdatedAt())));
 if(selected.contains("PROJECT"))em.createQuery("select p from Project p where p.user.id=:uid and (lower(p.name) like :q or lower(coalesce(p.description,'')) like :q) order by p.updatedAt desc",com.nivor.project.Project.class).setParameter("uid",uid).setParameter("q",q).setMaxResults(limit).getResultList().forEach(p->out.add(new SearchDtos.Result("PROJECT",p.getId(),p.getName(),p.getDescription(),"/workspace",p.getUpdatedAt())));
 if(selected.contains("GOAL"))em.createQuery("select g from Goal g where g.user.id=:uid and (lower(g.title) like :q or lower(coalesce(g.description,'')) like :q) order by g.updatedAt desc",com.nivor.goal.Goal.class).setParameter("uid",uid).setParameter("q",q).setMaxResults(limit).getResultList().forEach(g->out.add(new SearchDtos.Result("GOAL",g.getId(),g.getTitle(),g.getDescription(),"/goals",g.getUpdatedAt())));
 if(selected.contains("JOURNAL"))em.createQuery("select j from JournalEntry j where j.user.id=:uid and (lower(coalesce(j.title,'')) like :q or lower(j.content) like :q) order by j.updatedAt desc",com.nivor.journal.JournalEntry.class).setParameter("uid",uid).setParameter("q",q).setMaxResults(limit).getResultList().forEach(j->out.add(new SearchDtos.Result("JOURNAL",j.getId(),j.getTitle(),null,"/journal",j.getUpdatedAt())));
 if(selected.contains("EVENT"))em.createQuery("select e from CalendarEvent e where e.user.id=:uid and (lower(e.title) like :q or lower(coalesce(e.description,'')) like :q) order by e.updatedAt desc",com.nivor.planner.CalendarEvent.class).setParameter("uid",uid).setParameter("q",q).setMaxResults(limit).getResultList().forEach(e->out.add(new SearchDtos.Result("EVENT",e.getId(),e.getTitle(),e.getDescription(),"/planner",e.getUpdatedAt())));
 if(selected.contains("FILE"))files.searchOwned(uid,query.trim().toLowerCase(Locale.ROOT),null,null,PageRequest.of(0,limit)).getContent().forEach(f->out.add(new SearchDtos.Result("FILE",f.getId(),f.getOriginalName(),f.getMimeType(),"/files",f.getUpdatedAt())));
 return new SearchDtos.SearchResponse(out.stream().sorted(Comparator.comparing(SearchDtos.Result::updatedAt,Comparator.nullsLast(Comparator.reverseOrder()))).limit(limit*3L).toList());}}
